FROM ubuntu:16.04
WORKDIR /app
RUN apt-get update && \
    apt-get install -y  python3-pip python3.5
RUN pip3 install --upgrade pip setuptools 
COPY . .
RUN pip3 install -r requirements.txt
CMD [ "python3", "-u", "./edge_to_blob.py" ]

