FROM ubuntu:16.04
WORKDIR /app
RUN apt-get update && \
    #apt-get install -y  python3-pip python3.5
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python3-pip libboost-python1.58-dev libpython3-dev \
    python3.5  zip x11-apps lsb-core wget cpio sudo libpng-dev zlib1g-dev udev\
    libnuma1 ocl-icd-libopencl1 clinfo libboost-filesystem1.58.0 libboost-thread1.58.0 && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip setuptools 
COPY . .
RUN pip3 install -r requirements.txt
CMD [ "python3", "-u", "./edge_to_blob.py" ]

